# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodRisk2
                                 A QGIS plugin
 This plugin assist authorities for flood risk analysis and management
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-04
        copyright            : (C) 2018 by L.Mancusi/RSE S.p.A.
        email                : leonardo.mancusi@rse-web.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodRisk2 class from file FloodRisk2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .floodrisk2 import FloodRisk2
    return FloodRisk2(iface)
